services:
  - docker:dind

stages:
  - build-and-deploy

build-and-deploy:
  image: docker:stable
  stage: build-and-deploy
  script:
    - "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - "docker build -t blusky/tromino ."
    - "docker tag blusky/tromino $CI_REGISTRY/blusky/tromino:latest"
    - "docker push $CI_REGISTRY/blusky/tromino:latest"
